### ISSUE TITLE
Getting ToDouble() NoSuchMethodError

### ISSUE THREAD

**Issue by Csabatom** [AhmedAbouelkher/UI_SizeConfig-for-Flutter#3]
Everything implemented correctly, still getting this issue.
![FlutterDoctor](https://user-images.githubusercontent.com/55548572/83702392-df09c800-a60c-11ea-94ac-1226cdc33fb1.png)
![FlutterResponseError](https://user-images.githubusercontent.com/55548572/83702396-e29d4f00-a60c-11ea-90cb-b665fa05ff3c.png)

**Comment by AhmedAbouelkher** [comment]
This problem happens when trying to give a double argument a data type other than double.
Can you tack a screenshot of the actual code?

**Comment by Csabatom** [comment]
**This is my Code:**

`import 'package:flutter/material.dart';
import 'package:response/response.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: ResponseDemo()
    )
  );
}

class ResponseDemo extends StatefulWidget {
  ResponseDemo({Key key}) : super(key: key);

  @override
  _ResponseDemoState createState() => _ResponseDemoState();
}

class _ResponseDemoState extends State<ResponseDemo> {
  final response = ResponseUI.instance;
  @override
  Widget build(BuildContext context) {
    return Response(
      originalScreenHeight: 759,
      originalScreenWidth: 360,
      child: MaterialApp(
        home: Scaffold(
          backgroundColor: Colors.red,
          body: Container(
            width: response.setWidth(100),
            height: 100,
            color: Colors.blue,
          )
        )
      )
    );
  }
}`

**Comment by AhmedAbouelkher** [comment]
you have to MaterialApp widget stack on top of each other. the issue cause is to not initiate `Response` widget before getting `ResponseUI.instance`.
your code should lock like this:
```
import 'package:flutter/material.dart';
import 'package:response/response.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MaterialApp(
        home: Response(
          originalScreenHeight: 759,
          originalScreenWidth: 360,
          child: ResponseDemo(),
        ),
      ),
    ),
  );
}

class ResponseDemo extends StatefulWidget {
  ResponseDemo({Key key}) : super(key: key);

  @override
  _ResponseDemoState createState() => _ResponseDemoState();
}

class _ResponseDemoState extends State {
  final response = ResponseUI.instance;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      body: Container(
        width: response.setWidth(100),
        height: 100,
        color: Colors.blue,
      ),
    );
  }
}
```
to avoid any problems and to see a working example, see the package example, [here](https://github.com/AhmedAbouelkher/Response-for-Flutter/blob/master/example/lib/main.dart)

`
`

**Comment by Csabatom** [comment]
Thank you for your time, and for the help!
